GET http://localhost:3000/

###
GET http://localhost:3000/products/view-products

###
GET http://localhost:3000/products/spec-product/4

###
POST http://localhost:3000/products/add-product
Content-Type: application/json

    {
        "title": "newid post",
        "content": "hoppas detta funkar"
        
    }

   